// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadZip(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadZip'](arg1, arg2, arg3);
}

export function GatewayActivateModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['GatewayActivateModel'](arg1, arg2, arg3);
}

export function GatewayActivateSession(arg1, arg2) {
  return window['go']['main']['App']['GatewayActivateSession'](arg1, arg2);
}

export function GatewayAgentStatus(arg1, arg2) {
  return window['go']['main']['App']['GatewayAgentStatus'](arg1, arg2);
}

export function GatewayCreateModel(arg1, arg2) {
  return window['go']['main']['App']['GatewayCreateModel'](arg1, arg2);
}

export function GatewayCreateSession(arg1, arg2) {
  return window['go']['main']['App']['GatewayCreateSession'](arg1, arg2);
}

export function GatewayDeleteModel(arg1, arg2) {
  return window['go']['main']['App']['GatewayDeleteModel'](arg1, arg2);
}

export function GatewayDeleteSession(arg1, arg2) {
  return window['go']['main']['App']['GatewayDeleteSession'](arg1, arg2);
}

export function GatewayFetchFiles(arg1, arg2) {
  return window['go']['main']['App']['GatewayFetchFiles'](arg1, arg2);
}

export function GatewayFetchMonitor(arg1, arg2) {
  return window['go']['main']['App']['GatewayFetchMonitor'](arg1, arg2);
}

export function GatewayGetModelStages(arg1, arg2) {
  return window['go']['main']['App']['GatewayGetModelStages'](arg1, arg2);
}

export function GatewayGetSession(arg1, arg2) {
  return window['go']['main']['App']['GatewayGetSession'](arg1, arg2);
}

export function GatewayInvokeAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['GatewayInvokeAgent'](arg1, arg2, arg3);
}

export function GatewayListModels(arg1) {
  return window['go']['main']['App']['GatewayListModels'](arg1);
}

export function GatewayListSessions(arg1) {
  return window['go']['main']['App']['GatewayListSessions'](arg1);
}

export function GatewayListSources(arg1) {
  return window['go']['main']['App']['GatewayListSources'](arg1);
}

export function GatewayLogin(arg1) {
  return window['go']['main']['App']['GatewayLogin'](arg1);
}

export function GatewayReadSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['GatewayReadSnapshot'](arg1, arg2, arg3);
}

export function GatewaySetModelStages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GatewaySetModelStages'](arg1, arg2, arg3, arg4);
}

export function GatewayStartStream(arg1) {
  return window['go']['main']['App']['GatewayStartStream'](arg1);
}

export function GatewayStopAgent(arg1, arg2) {
  return window['go']['main']['App']['GatewayStopAgent'](arg1, arg2);
}

export function GatewayStopStream() {
  return window['go']['main']['App']['GatewayStopStream']();
}

export function GatewayUpdateModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['GatewayUpdateModel'](arg1, arg2, arg3);
}

export function GatewayUpdateSessionSources(arg1, arg2, arg3) {
  return window['go']['main']['App']['GatewayUpdateSessionSources'](arg1, arg2, arg3);
}

export function GetBackendURL() {
  return window['go']['main']['App']['GetBackendURL']();
}

export function GetGatewayURL() {
  return window['go']['main']['App']['GetGatewayURL']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function Proxy(arg1) {
  return window['go']['main']['App']['Proxy'](arg1);
}

export function SetBackendURL(arg1) {
  return window['go']['main']['App']['SetBackendURL'](arg1);
}

export function SetGatewayURL(arg1) {
  return window['go']['main']['App']['SetGatewayURL'](arg1);
}

export function StartChatStream(arg1, arg2) {
  return window['go']['main']['App']['StartChatStream'](arg1, arg2);
}

export function StopChatStream() {
  return window['go']['main']['App']['StopChatStream']();
}

export function UploadDataset(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDataset'](arg1, arg2, arg3);
}

export function UploadDatasetFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDatasetFolder'](arg1, arg2, arg3);
}

export function WorkspaceDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WorkspaceDownload'](arg1, arg2, arg3, arg4);
}

export function WorkspaceUploadFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WorkspaceUploadFiles'](arg1, arg2, arg3, arg4);
}

export function WorkspaceUploadZip(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WorkspaceUploadZip'](arg1, arg2, arg3, arg4);
}
