// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadZip(arg1:Array<string>,arg2:string,arg3:string):Promise<main.FilePayload>;

export function GatewayActivateSession(arg1:string,arg2:string):Promise<main.GatewaySession>;

export function GatewayAgentStatus(arg1:string,arg2:string):Promise<main.GatewayAgentStatus>;

export function GatewayCreateSession(arg1:string,arg2:Array<string>):Promise<main.GatewaySession>;

export function GatewayDeleteSession(arg1:string,arg2:string):Promise<void>;

export function GatewayFetchFiles(arg1:string,arg2:string):Promise<main.FileTreeResponse>;

export function GatewayGetSession(arg1:string,arg2:string):Promise<main.GatewaySession>;

export function GatewayInvokeAgent(arg1:string,arg2:string,arg3:main.GatewayInvokeRequest):Promise<main.GatewayTaskSnapshot>;

export function GatewayListSessions(arg1:string):Promise<main.GatewaySessionsResponse>;

export function GatewayListSources(arg1:string):Promise<Array<main.GatewaySourceInfo>>;

export function GatewayLogin(arg1:main.GatewayLoginRequest):Promise<main.GatewayLoginResult>;

export function GatewayReadSnapshot(arg1:string,arg2:string,arg3:string):Promise<main.GatewaySnapshot>;

export function GatewayStartStream(arg1:string):Promise<void>;

export function GatewayStopAgent(arg1:string,arg2:string):Promise<main.GatewayTaskSnapshot>;

export function GatewayStopStream():Promise<void>;

export function GatewayUpdateSessionSources(arg1:string,arg2:string,arg3:Array<string>):Promise<main.GatewaySession>;

export function GetBackendURL():Promise<string>;

export function GetGatewayURL():Promise<string>;

export function Proxy(arg1:main.ProxyRequest):Promise<main.ProxyResponse>;

export function SetBackendURL(arg1:string):Promise<void>;

export function SetGatewayURL(arg1:string):Promise<void>;

export function StartChatStream(arg1:string,arg2:string):Promise<void>;

export function StopChatStream():Promise<void>;

export function UploadDataset(arg1:main.UploadedFile,arg2:string,arg3:string):Promise<main.UploadResult>;

export function UploadDatasetFolder(arg1:Array<main.UploadedFile>,arg2:string,arg3:string):Promise<main.UploadResult>;

export function WorkspaceDownload(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.FilePayload>;

export function WorkspaceUploadFiles(arg1:string,arg2:string,arg3:string,arg4:Array<main.UploadedFile>):Promise<main.WorkspaceUploadResult>;

export function WorkspaceUploadZip(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.WorkspaceDirUploadResult>;
